baseURL: /
languageCode: en-us
title: Jacob Rodal
theme: fluency
copyright: Jacob Rodal
enableRobotsTXT: true
paginate: 25
summaryLength: 100
markup:
  defaultMarkdownHandler: goldmark
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  highlight:
    guessSyntax: false
    lineNos: true
    noClasses: true
    lineNumbersInTable: true
  goldmark:
    renderer:
      unsafe: true
Author:
  name: Jacob Rodal
params:
  disableComment: false
  disableCommentByType:
    - page
    - about
  thirdPartyComment: |
    <script src="https://utteranc.es/client.js"
        repo="jrodal98/website"
        issue-term="url"
        theme="preferred-color-scheme"
        crossorigin="anonymous"
        async>
    </script>
  mainSections:
    - posts
    - tags
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - name: Archives
      identifier: archives
      url: /archives/
      weight: 3
    - name: About
      identifier: about
      url: /about/
      weight: 4
  footer:
    - identifier: github
      url: "https://github.com/jrodal98"
      name: Github
    - identifier: linkedin
      url: "https://www.linkedin.com/in/jacob-rodal"
      name: LinkedIn
